// <auto-generated />
using System;
using CRD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRD.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507160955_WorkflowUpdateModel")]
    partial class WorkflowUpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRD.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CRD.Domain.Entities.CRDFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DistrictRateId")
                        .HasColumnType("int");

                    b.Property<string>("FileClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictRateId");

                    b.HasIndex("PlantId");

                    b.ToTable("CRDFiles");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CRD.Domain.Entities.CategoryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TreeId");

                    b.ToTable("CategoryInfo");
                });

            modelBuilder.Entity("CRD.Domain.Entities.CompensationRateModeration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeferredReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscretionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeferred")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModerationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModerationNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moderator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewDiscretionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NewRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlantRateId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StructureRateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantRateId");

                    b.HasIndex("StructureRateId");

                    b.ToTable("CompensationRateModerations");
                });

            modelBuilder.Entity("CRD.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("CRD.Domain.Entities.DistrictRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("UploadIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("DistrictRates");
                });

            modelBuilder.Entity("CRD.Domain.Entities.GroupedPlantItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<int>("GroupedPlantId")
                        .HasColumnType("int");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("GroupedPlantId");

                    b.HasIndex("TreeId");

                    b.ToTable("GroupedPlantItems");
                });

            modelBuilder.Entity("CRD.Domain.Entities.GroupedPlants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.PrimitiveCollection<string>("GrowthStages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GroupedPlants");
                });

            modelBuilder.Entity("CRD.Domain.Entities.GrowthStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrowthStages");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Languange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languanges");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BotanicalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.PrimitiveCollection<string>("GrowthStages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Plant");

                    b.HasDiscriminator().HasValue("Plant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CRD.Domain.Entities.PlantRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assumptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryInfoOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeferredReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeferredReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscretionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictRateId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupedPlantId")
                        .HasColumnType("int");

                    b.Property<int>("GrowthStageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewDeferred")
                        .HasColumnType("bit");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<int?>("PlantId1")
                        .HasColumnType("int");

                    b.Property<string>("PlantType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryInfoId");

                    b.HasIndex("DistrictRateId");

                    b.HasIndex("GroupedPlantId");

                    b.HasIndex("PlantId");

                    b.HasIndex("PlantId1");

                    b.ToTable("PlantRates");
                });

            modelBuilder.Entity("CRD.Domain.Entities.PlantRateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("PlantRateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("PlantRateId");

                    b.ToTable("PlantRateGroups");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Structure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StructureTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StructureTypeId");

                    b.ToTable("Structures");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("StructureAttributes");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureAttributeSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("StructureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("StructureId");

                    b.ToTable("StructureAttributeSelections");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StructureCategories");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("StructureOptions");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureOptionSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeSelectionId")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeSelectionId");

                    b.HasIndex("OptionId");

                    b.ToTable("StructureOptionSelections");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assumptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeferredReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeferredReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscretionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictRateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReviewDeferred")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StructureId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictRateId");

                    b.HasIndex("StructureId");

                    b.ToTable("StructureRates");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StructureTypes");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Translated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("CRD.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CRD.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CRD.Domain.Process.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictWorkflowStepId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictWorkflowSubStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DistrictWorkflowStepId");

                    b.HasIndex("DistrictWorkflowSubStepId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("DistrictWorkflow");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictWorkflowId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictWorkflowId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("DistrictWorkflowStep");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflowSubStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictWorkflowStepId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowSubStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictWorkflowStepId");

                    b.HasIndex("WorkflowSubStepId");

                    b.ToTable("DistrictWorkflowSubStep");
                });

            modelBuilder.Entity("CRD.Domain.Process.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictWorkflowStepId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictWorkflowSubStepId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DistrictWorkflowStepId");

                    b.HasIndex("DistrictWorkflowSubStepId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CRD.Domain.Process.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("CRD.Domain.Process.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NextStepId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStepId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("CRD.Domain.Process.WorkflowSubStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowStepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("WorkflowSubSteps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CRD.Domain.Entities.Crop", b =>
                {
                    b.HasBaseType("CRD.Domain.Entities.Plant");

                    b.Property<string>("Aez")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CropType")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Crop");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Tree", b =>
                {
                    b.HasBaseType("CRD.Domain.Entities.Plant");

                    b.PrimitiveCollection<string>("Othernames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Tree");
                });

            modelBuilder.Entity("CRD.Domain.Entities.CRDFile", b =>
                {
                    b.HasOne("CRD.Domain.Entities.DistrictRate", null)
                        .WithMany("Uploads")
                        .HasForeignKey("DistrictRateId");

                    b.HasOne("CRD.Domain.Entities.Plant", null)
                        .WithMany("Images")
                        .HasForeignKey("PlantId");
                });

            modelBuilder.Entity("CRD.Domain.Entities.CategoryInfo", b =>
                {
                    b.HasOne("CRD.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.Plant", null)
                        .WithMany("CategoryInform")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CRD.Domain.Entities.CompensationRateModeration", b =>
                {
                    b.HasOne("CRD.Domain.Entities.PlantRate", "PlantRate")
                        .WithMany("ModerationHistory")
                        .HasForeignKey("PlantRateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CRD.Domain.Entities.StructureRate", "StructureRate")
                        .WithMany("ModerationHistory")
                        .HasForeignKey("StructureRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlantRate");

                    b.Navigation("StructureRate");
                });

            modelBuilder.Entity("CRD.Domain.Entities.DistrictRate", b =>
                {
                    b.HasOne("CRD.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("CRD.Domain.Entities.GroupedPlantItem", b =>
                {
                    b.HasOne("CRD.Domain.Entities.Crop", "Crop")
                        .WithMany("GroupedPlantItems")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRD.Domain.Entities.GroupedPlants", "GroupedPlant")
                        .WithMany("GroupedPlantItems")
                        .HasForeignKey("GroupedPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.Tree", "Tree")
                        .WithMany("GroupedPlantItems")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Crop");

                    b.Navigation("GroupedPlant");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("CRD.Domain.Entities.PlantRate", b =>
                {
                    b.HasOne("CRD.Domain.Entities.CategoryInfo", "CategoryInfo")
                        .WithMany()
                        .HasForeignKey("CategoryInfoId");

                    b.HasOne("CRD.Domain.Entities.DistrictRate", "DistrictRate")
                        .WithMany("PlantRates")
                        .HasForeignKey("DistrictRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.GroupedPlants", "GroupedPlants")
                        .WithMany()
                        .HasForeignKey("GroupedPlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRD.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CRD.Domain.Entities.Plant", null)
                        .WithMany("PlantRates")
                        .HasForeignKey("PlantId1");

                    b.Navigation("CategoryInfo");

                    b.Navigation("DistrictRate");

                    b.Navigation("GroupedPlants");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("CRD.Domain.Entities.PlantRateGroup", b =>
                {
                    b.HasOne("CRD.Domain.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.PlantRate", "PlantRate")
                        .WithMany("PlantRateGroups")
                        .HasForeignKey("PlantRateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("PlantRate");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Structure", b =>
                {
                    b.HasOne("CRD.Domain.Entities.StructureCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.StructureType", "StructureType")
                        .WithMany()
                        .HasForeignKey("StructureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("StructureType");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureAttribute", b =>
                {
                    b.HasOne("CRD.Domain.Entities.StructureCategory", "Category")
                        .WithMany("Attributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureAttributeSelection", b =>
                {
                    b.HasOne("CRD.Domain.Entities.StructureAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.Structure", "Structure")
                        .WithMany("AttributeSelections")
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureOption", b =>
                {
                    b.HasOne("CRD.Domain.Entities.StructureAttribute", "Attribute")
                        .WithMany("Options")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureOptionSelection", b =>
                {
                    b.HasOne("CRD.Domain.Entities.StructureAttributeSelection", "AttributeSelection")
                        .WithMany("OptionSelections")
                        .HasForeignKey("AttributeSelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.StructureOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeSelection");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureRate", b =>
                {
                    b.HasOne("CRD.Domain.Entities.DistrictRate", "DistrictRate")
                        .WithMany("StructureRates")
                        .HasForeignKey("DistrictRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Entities.Structure", "Structure")
                        .WithMany()
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistrictRate");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Translation", b =>
                {
                    b.HasOne("CRD.Domain.Entities.Plant", null)
                        .WithMany("Translations")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CRD.Domain.Process.Comment", b =>
                {
                    b.HasOne("CRD.Domain.Process.DistrictWorkflowStep", "DistrictWorkflowStep")
                        .WithMany("Comments")
                        .HasForeignKey("DistrictWorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CRD.Domain.Process.DistrictWorkflowSubStep", "DistrictWorkflowSubStep")
                        .WithMany("Comments")
                        .HasForeignKey("DistrictWorkflowSubStepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DistrictWorkflowStep");

                    b.Navigation("DistrictWorkflowSubStep");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflow", b =>
                {
                    b.HasOne("CRD.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Process.Workflow", "Workflow")
                        .WithMany("DistrictWorkflows")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflowStep", b =>
                {
                    b.HasOne("CRD.Domain.Process.DistrictWorkflow", "DistrictWorkflow")
                        .WithMany("DistrictSteps")
                        .HasForeignKey("DistrictWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Process.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DistrictWorkflow");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflowSubStep", b =>
                {
                    b.HasOne("CRD.Domain.Process.DistrictWorkflowStep", "DistrictWorkflowStep")
                        .WithMany("DistrictSubSteps")
                        .HasForeignKey("DistrictWorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Process.WorkflowSubStep", "WorkflowSubStep")
                        .WithMany()
                        .HasForeignKey("WorkflowSubStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DistrictWorkflowStep");

                    b.Navigation("WorkflowSubStep");
                });

            modelBuilder.Entity("CRD.Domain.Process.Document", b =>
                {
                    b.HasOne("CRD.Domain.Process.DistrictWorkflowStep", "DistrictWorkflowStep")
                        .WithMany("Documents")
                        .HasForeignKey("DistrictWorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CRD.Domain.Process.DistrictWorkflowSubStep", "DistrictWorkflowSubStep")
                        .WithMany("Documents")
                        .HasForeignKey("DistrictWorkflowSubStepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DistrictWorkflowStep");

                    b.Navigation("DistrictWorkflowSubStep");
                });

            modelBuilder.Entity("CRD.Domain.Process.WorkflowStep", b =>
                {
                    b.HasOne("CRD.Domain.Process.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("CRD.Domain.Process.WorkflowSubStep", b =>
                {
                    b.HasOne("CRD.Domain.Process.WorkflowStep", "WorkflowStep")
                        .WithMany("SubSteps")
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("CRD.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CRD.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CRD.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("CRD.Domain.Identity.ApplicationRole", null)
                        .WithMany("Users")
                        .HasForeignKey("ApplicationRoleId");

                    b.HasOne("CRD.Domain.Identity.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("CRD.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRD.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CRD.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CRD.Domain.Entities.DistrictRate", b =>
                {
                    b.Navigation("PlantRates");

                    b.Navigation("StructureRates");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("CRD.Domain.Entities.GroupedPlants", b =>
                {
                    b.Navigation("GroupedPlantItems");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Plant", b =>
                {
                    b.Navigation("CategoryInform");

                    b.Navigation("Images");

                    b.Navigation("PlantRates");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CRD.Domain.Entities.PlantRate", b =>
                {
                    b.Navigation("ModerationHistory");

                    b.Navigation("PlantRateGroups");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Structure", b =>
                {
                    b.Navigation("AttributeSelections");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureAttribute", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureAttributeSelection", b =>
                {
                    b.Navigation("OptionSelections");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureCategory", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("CRD.Domain.Entities.StructureRate", b =>
                {
                    b.Navigation("ModerationHistory");
                });

            modelBuilder.Entity("CRD.Domain.Identity.ApplicationRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRD.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflow", b =>
                {
                    b.Navigation("DistrictSteps");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflowStep", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DistrictSubSteps");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CRD.Domain.Process.DistrictWorkflowSubStep", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CRD.Domain.Process.Workflow", b =>
                {
                    b.Navigation("DistrictWorkflows");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CRD.Domain.Process.WorkflowStep", b =>
                {
                    b.Navigation("SubSteps");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Crop", b =>
                {
                    b.Navigation("GroupedPlantItems");
                });

            modelBuilder.Entity("CRD.Domain.Entities.Tree", b =>
                {
                    b.Navigation("GroupedPlantItems");
                });
#pragma warning restore 612, 618
        }
    }
}
