services:
 crd.api:
    image: ${DOCKER_REGISTRY-}crdapi
    build:
      context: .
      dockerfile: CRD.API/Dockerfile
    ports:
       - "5100:5100"
    environment:
      - ASPNETCORE_URLS=http://+:5100
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=crd-mssql-db;User Id=sa;Password=Str0p@ssword;Encrypt=false;
      - MongoDb__ConnectionString=mongodb://admin:password@localhost:27017/admin
      - MongoDb__DatabaseName=CRD
      - MongoDb__CollectionName=PublishedRateDocuments
      - MailSettings__Mail=notifications@redahug.com
      - MailSettings__DisplayName=Notifications
      - MailSettings__Password=Notify@123
      - MailSettings__Host=smtp.office365.com
      - MailSettings__Port=587
      - MailSettings__AppUrl=http://172.16.24.56
      - CorsSettings__AllowedOrigins=["http://localhost:5100", "http://localhost","http://172.16.24.56"]

 mongo:
    container_name: crd-mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongo-data:/data/db
 mssql:
    container_name: crd-mssql-db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Str0p@ssword"
    volumes:
      - mssql-data:/var/opt/mssql
volumes:
    mssql-data:
    mongo-data:
